### ISSUE TITLE
Failed when having export default from imported

### ISSUE THREAD

**Issue by cowardcalf** [afterwind-io/preprocessor-loader#4]
Hi, @afterwind-io 

I've found this loader does not work in the case when having export default from another imported default module.

For example,
```javascript
// File ./components/a.js
const someFunc = () => { // do something };
export default someFunc;
```

```javascript
// File ./components/index.js
import someFunc from "./a"
export default someFunc;
```

```javascript
// File app.js
import someFunc from "./components"

someFunc();
```

It will throw errors when compling
>> WARNING in app.js
"export 'default' (imported as 'someFunc') was not found in 'app.js'

It would be glad to see any response from you.
Thanks.

**Comment by cowardcalf** [comment]
Actually, I've found that was caused by missing the empty line at the end of the `.js` file.
The issue will be gone when adding an empty line to each of the source file.

Interesting.

**Comment by afterwind-io** [comment]
@cowardcalf
Sorry for the delay. I'll look into it soon.

**Comment by afterwind-io** [comment]
@cowardcalf 
Surprisingly this bug lasts so long. If there is no new line at the end of the code, the last line will be skipped, because an inner state flag collects a single line never gets a chance to end itself.

Anyway thanks for the issue. v1.1.1 has solved the problem. Try it out!
https://www.npmjs.com/package/webpack-preprocessor-loader/v/1.1.1

**Comment by cowardcalf** [comment]
@afterwind-io 
Thanks for the quick response and the immediate fixing.
I'll try the new fresh v1.1.1 release.

Are you going to close this issue?

**Comment by afterwind-io** [comment]
@cowardcalf 
Seems the actual flaw is a little more tricky than I have thought. The problem here is what on the last line(single/multiple characters in this case, which I was missing), rather than file format.

I have bumped another update to cover more cases. It should be working now.
https://www.npmjs.com/package/webpack-preprocessor-loader/v/1.1.2

**Comment by cowardcalf** [comment]
That's a quick fixing.
Yes, I guess it was file format irrelevant.
I'll try the new release soon.
Thanks again.

**Comment by cowardcalf** [comment]
@afterwind-io 
I've tested new release. So far so good.
Thank you for your efforts.
